import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>SmartChange - Sign Up</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className="main">

                <div className="bottom-grid">
                    <div className="logo">
                        <Image
                            src="/logo.png"
                            alt="Picture of the author"
                            width={100}
                            height={30}
                        />
                    </div>
                </div>
                <div className="content-w3ls">

                    <div className="content-bottom">
                        <form action="#" method="post">
                            <div className="field-group">
                                <span className="fa fa-user" aria-hidden="true"></span>
                                <div className="wthree-field">
                                    <input name="text1" id="text1" type="text" placeholder="Email address" required />
                                </div>
                            </div>
                            <div className="field-group">
                                <span className="fa fa-user" aria-hidden="true"></span>
                                <div className="wthree-field">
                                    <input name="text1" id="text1" type="text" placeholder="Email address" required />
                                </div>
                            </div>
                            <div className="field-group">
                                <span className="fa fa-user" aria-hidden="true"></span>
                                <div className="wthree-field">
                                    <input name="text1" id="text1" type="text" placeholder="Email address" required />
                                </div>
                            </div>
                            <div className="field-group">
                                <span className="fa fa-lock" aria-hidden="true"></span>
                                <div className="wthree-field">
                                    <input name="password" id="myInput" type="Password" placeholder="Password" />
                                </div>
                            </div>
                            <div className="wthree-field">
                                <button type="submit" className="btn">Sign in</button>
                            </div>
                            <ul className="list-login">
                                <li>
                                    <a href="#" className="text-right" style={{ fontWeight: 'bold' }}>forgot password?</a>
                                </li>
                                <li className="clearfix"></li>
                            </ul>
                            <ul className="list-login-bottom">
                                <li className="">
                                    <a href="#url" className="">Create Account</a>
                                </li>
                                <li className="clearfix"></li>
                            </ul>
                        </form>
                    </div>
                </div>
            </section>


        </>
    )
}
